version: 2
updates:
  - package-ecosystem: nuget
    directory: "/AdventOfCode"
    schedule:
      interval: daily
      time: "21:00"
  - package-ecosystem: nuget
    directory: "/Tests"
    schedule:
      interval: daily
      time: "21:00"
