version: 1
update_configs:
  # 2019 - Day 1
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day1/Solution/"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day1/Tests/"
    update_schedule: "live"
  # 2019 - Day 2
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day2/Solution/"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day2/Tests/"
    update_schedule: "live"
  # 2019 - Day 3
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day3/Solution/"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day3/Tests/"
    update_schedule: "live"
  # 2019 - Day 4
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day4/Solution/"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day4/Tests/"
    update_schedule: "live"
  # 2019 - Day 5
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day5/Solution/"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day5/Tests/"
    update_schedule: "live"
  # 2019 - Day 6
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day6/Solution/"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day6/Tests/"
    update_schedule: "live"