version: 1
update_configs:
  # 2019 - Day 1
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day1/Solution/"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day1/Tests/"
    update_schedule: "live"
  # 2019 - Day 2
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day2/Solution/"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day2/Tests/"
    update_schedule: "live"
  # 2019 - Day 3
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day3/Solution/"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/2019/Day3/Tests/"
    update_schedule: "live"
