name: CI

on:
  push:
    branches: [master]
    paths: "AdventOfCode/**"
  pull_request:
    branches: [master]
    paths: "AdventOfCode/**"

jobs:
  Build_and_Test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.1
      - name: Install dependencies for Solution
        run: dotnet restore AdventOfCode.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore AdventOfCode.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal AdventOfCode.sln
